# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.response_get_users_data import ResponseGetUsersData  # noqa: F401,E501
from swagger_server import util


class ResponseGetUsers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: str=None, message: str=None, data: ResponseGetUsersData=None):  # noqa: E501
        """ResponseGetUsers - a model defined in Swagger

        :param code: The code of this ResponseGetUsers.  # noqa: E501
        :type code: str
        :param message: The message of this ResponseGetUsers.  # noqa: E501
        :type message: str
        :param data: The data of this ResponseGetUsers.  # noqa: E501
        :type data: ResponseGetUsersData
        """
        self.swagger_types = {
            'code': str,
            'message': str,
            'data': ResponseGetUsersData
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }
        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetUsers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetUsers of this ResponseGetUsers.  # noqa: E501
        :rtype: ResponseGetUsers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this ResponseGetUsers.


        :return: The code of this ResponseGetUsers.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ResponseGetUsers.


        :param code: The code of this ResponseGetUsers.
        :type code: str
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetUsers.


        :return: The message of this ResponseGetUsers.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetUsers.


        :param message: The message of this ResponseGetUsers.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> ResponseGetUsersData:
        """Gets the data of this ResponseGetUsers.


        :return: The data of this ResponseGetUsers.
        :rtype: ResponseGetUsersData
        """
        return self._data

    @data.setter
    def data(self, data: ResponseGetUsersData):
        """Sets the data of this ResponseGetUsers.


        :param data: The data of this ResponseGetUsers.
        :type data: ResponseGetUsersData
        """

        self._data = data
