# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ResponseGetUsersData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, user_name: str=None, full_name: str=None, email: str=None, rol_id: int=None, rol_name: str=None):  # noqa: E501
        """ResponseGetUsersData - a model defined in Swagger

        :param id: The id of this ResponseGetUsersData.  # noqa: E501
        :type id: int
        :param user_name: The user_name of this ResponseGetUsersData.  # noqa: E501
        :type user_name: str
        :param full_name: The full_name of this ResponseGetUsersData.  # noqa: E501
        :type full_name: str
        :param email: The email of this ResponseGetUsersData.  # noqa: E501
        :type email: str
        :param rol_id: The rol_id of this ResponseGetUsersData.  # noqa: E501
        :type rol_id: int
        :param rol_name: The rol_name of this ResponseGetUsersData.  # noqa: E501
        :type rol_name: str
        """
        self.swagger_types = {
            'id': int,
            'user_name': str,
            'full_name': str,
            'email': str,
            'rol_id': int,
            'rol_name': str
        }

        self.attribute_map = {
            'id': 'id',
            'user_name': 'user_name',
            'full_name': 'full_name',
            'email': 'email',
            'rol_id': 'rol_id',
            'rol_name': 'rol_name'
        }
        self._id = id
        self._user_name = user_name
        self._full_name = full_name
        self._email = email
        self._rol_id = rol_id
        self._rol_name = rol_name

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetUsersData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetUsers_data of this ResponseGetUsersData.  # noqa: E501
        :rtype: ResponseGetUsersData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ResponseGetUsersData.


        :return: The id of this ResponseGetUsersData.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ResponseGetUsersData.


        :param id: The id of this ResponseGetUsersData.
        :type id: int
        """

        self._id = id

    @property
    def user_name(self) -> str:
        """Gets the user_name of this ResponseGetUsersData.


        :return: The user_name of this ResponseGetUsersData.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name: str):
        """Sets the user_name of this ResponseGetUsersData.


        :param user_name: The user_name of this ResponseGetUsersData.
        :type user_name: str
        """

        self._user_name = user_name

    @property
    def full_name(self) -> str:
        """Gets the full_name of this ResponseGetUsersData.


        :return: The full_name of this ResponseGetUsersData.
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name: str):
        """Sets the full_name of this ResponseGetUsersData.


        :param full_name: The full_name of this ResponseGetUsersData.
        :type full_name: str
        """

        self._full_name = full_name

    @property
    def email(self) -> str:
        """Gets the email of this ResponseGetUsersData.


        :return: The email of this ResponseGetUsersData.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this ResponseGetUsersData.


        :param email: The email of this ResponseGetUsersData.
        :type email: str
        """

        self._email = email

    @property
    def rol_id(self) -> int:
        """Gets the rol_id of this ResponseGetUsersData.


        :return: The rol_id of this ResponseGetUsersData.
        :rtype: int
        """
        return self._rol_id

    @rol_id.setter
    def rol_id(self, rol_id: int):
        """Sets the rol_id of this ResponseGetUsersData.


        :param rol_id: The rol_id of this ResponseGetUsersData.
        :type rol_id: int
        """

        self._rol_id = rol_id

    @property
    def rol_name(self) -> str:
        """Gets the rol_name of this ResponseGetUsersData.


        :return: The rol_name of this ResponseGetUsersData.
        :rtype: str
        """
        return self._rol_name

    @rol_name.setter
    def rol_name(self, rol_name: str):
        """Sets the rol_name of this ResponseGetUsersData.


        :param rol_name: The rol_name of this ResponseGetUsersData.
        :type rol_name: str
        """

        self._rol_name = rol_name
